AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 Instance using CloudFormation

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1d
      ImageId: ami-068c0051b15cdb816
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: ProgressEC2Instance

